# Generated by Django 5.0.11 on 2025-01-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.TextField()),
                ("author_email", models.EmailField(max_length=254)),
                ("author_date", models.DateField()),
            ],
        ),
    ]
