# Generated by Django 5.0.11 on 2025-01-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("school", models.TextField(max_length=200)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_programme", models.TextField(max_length=200)),
            ],
        ),
    ]
